version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nest-app:
    build: .
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://username:password@mysql:3306/database
    depends_on:
      - mysql

volumes:
  mysql-data:
